# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Home',               url: 'index'}
- {name: 'Resources',          url: 'resources'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
# - {name: 'About',              url: 'about'}
- {name: 'Join Us!',           url: 'join'}
- {name: 'Contact',            url: 'contact'} 

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:    'https://www.linkedin.com/company/mccormack-strategy-and-analytics-club-umass/'}
- {icon: 'instagram', link:  'https://www.instagram.com/mccormackumass/'}
# - {icon: 'facebook', link:   'https://www.facebook.com/profile.php?id=100094054570514'}
- {icon: 'envelope', link:   'mailto:msaumass1@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
